[package]
name = "rust-in-c"
version = "0.1.0"
edition = "2024"

[lib]
name = "rust_in_c"
crate-type = ["cdylib", "staticlib"]

[dependencies]
cargo-post = "0.1.7"

[build-dependencies]
cbindgen = "0.29.0"
